version: '3'
services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: christmas-akinator
      MYSQL_DATABASE: christmas-akinator
    ports:
      - "3306:3306"

  api:
    build: .
    command: bundle exec rails s -p 9000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    links:
      - db
    